The thrown Exception: Error can not connect to server. 
se.kth.iv1350.sempos.Integration.DatabaseFailureException: Error can not connect to server. 
	at se.kth.iv1350.sempos.Integration.InventorySystem.getItemInformation(InventorySystem.java:31)
	at se.kth.iv1350.sempos.controller.Controller.registerItem(Controller.java:51)
	at se.kth.iv1350.sempos.view.View.scanItem(View.java:94)
	at se.kth.iv1350.sempos.view.View.runFakeExecution(View.java:47)
	at se.kth.iv1350.sempos.startup.Main.main(Main.java:27)


