, The thrown Exception: Error can not connect to server. Item does not exists.4
se.kth.iv1350.sempos.Integration.DatabaseFailureException: Error can not connect to server. Item does not exists.4
	at se.kth.iv1350.sempos.Integration.InventorySystem.getItemInformation(InventorySystem.java:34)
	at se.kth.iv1350.sempos.controller.Controller.registerItem(Controller.java:48)
	at se.kth.iv1350.sempos.view.View.scanItem(View.java:59)
	at se.kth.iv1350.sempos.view.View.runFakeExecution(View.java:37)
	at se.kth.iv1350.sempos.startup.Main.main(Main.java:27)


